cijfer = input("wat is je cijfer?(Type cijfer_en dan cijfer getal!)")
cijfer_1 = ("zeer slecht")
if (cijfer_1): print("zeer slecht")
cijfer_2 = ("slecht")
if (cijfer_2): print("slecht")
cijfer_3 = ("gering")
if (cijfer_3): print("gering")
cijfer_4 = ("onvoldoende")
if (cijfer_4): print("onvoldoende")
cijfer_5 = ("bijna voldoende")
if (cijfer_5): print("bijna voldoende")
cijfer_6 = ("voldoende")
if (cijfer_6): print("voldoende")
cijfer_7 = ("ruim voldoende")
if (cijfer_7): print("ruim voldoende")
cijfer_8 = ("goed")
if (cijfer_8): print("goed")
cijfer_9 = ("zeer goed")
if (cijfer_9): print("zeer goed")
cijfer_10 = ("uitmuntend")
if (cijfer_10): print("uitmuntend")

# ik weet dat er hier niet een cijver uitkomt maar ik weet niet een andere manier om dit te coderen
# ik weet niet waarom het niet werkt
# zie schermafbeeldingen