naam_1 = input("Hoe heet je?")
woord_1= input("Wat voor soort dag moet het zijn?")
stad_1= input("welke stad?")
woord_3= input("Waar ben je naar op zoek?")
woord_4= input("wat voor man of vrouw?")
woord_5= input("wat verkoopt deze man of vrouw?")
woord_6= input("je kwam bij wat?")
woordzin_7= input("wat doen de groep mensen?")

print("Het was een " + woord_1 + " dag in " + stad_1 + " . " + naam_1 + " liep door de straten, op zoek naar een " + woord_3 + " . " + " Plotseling zag " + naam_1 + " een " + woord_4 + " man/vrouw die een " + woord_5 + " verkocht. " + naam_1 + " besloot om het te kopen en liep verder. " + " Toen " + naam_1 + " bij een " + woord_6 + " kwam, zag hij/zij een groep mensen die " + woordzin_7 + " . " + naam_1 + " besloot om mee te doen en had de tijd van zijn/haar leven. ")